---
- name: Create netbootxyz docker container
  community.docker.docker_container:
    state: started
    container_default_behavior: no_defaults
    name: netbootxyz
    image: linuxserver/netbootxyz
    restart_policy: unless-stopped
    env:
      PUID: '{{ netbootxyz_user_id | string }}'
      GUID: '{{ netbootxyz_group_id | string }}'
    ports:
      - 69:69/udp
      - 3000:3000
      - 8080:80
    volumes:
      - '{{ netbootxyz_path }}/config:/config'
      - '{{ netbootxyz_path }}/assets:/assets'

- name: Pause until container downloads assets
  ansible.builtin.pause:
    seconds: 5

- name: Copy local-vars.ipxe
  ansible.builtin.template:
    src: templates/local-vars.ipxe.j2
    dest: "{{ netbootxyz_path }}/config/menus/local-vars.ipxe"
    mode: 0644

- name: Copy menu.ipxe
  ansible.builtin.template:
    src: templates/menu.ipxe.j2
    dest: "{{ netbootxyz_path }}/config/menus/menu.ipxe"
    mode: 0644    

- name: Copy boot.cfg
  ansible.builtin.template:
    src: templates/boot.cfg.j2
    dest: "{{ netbootxyz_path }}/config/menus/boot.cfg"
    mode: 0644

- name: Copy windows.ipxe
  ansible.builtin.template:
    src: templates/windows.ipxe.j2
    dest: "{{ netbootxyz_path }}/config/menus/windows.ipxe"
    mode: 0644

- name: Copy remote/menu.ipxe
  ansible.builtin.template:
    src: templates/menu.ipxe.j2
    dest: "{{ netbootxyz_path }}/config/menus/remote/menu.ipxe"
    mode: 0644

- name: Copy remote/boot.cfg
  ansible.builtin.template:
    src: templates/boot.cfg.j2
    dest: "{{ netbootxyz_path }}/config/menus/remote/boot.cfg"
    mode: 0644

- name: Copy remote/windows.ipxe
  ansible.builtin.template:
    src: templates/windows.ipxe.j2
    dest: "{{ netbootxyz_path }}/config/menus/remote/windows.ipxe"
    mode: 0644
